version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT
      - DATABASE_NAME
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - PUBLIC_URL
      - IS_PROXIED
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'